### ISSUE TITLE
[Off Topic]Which tool made so cute terminal screenshot?

### ISSUE THREAD

**Issue by leopku** [essentialkaos/aligo#187]
Sorry for this off-topic question, but the screenshot was so cute.

Did you use some tool like freeze to make it?

 ![](https://github.com/essentialkaos/aligo/raw/master/.github/images/usage.svg)

**Comment by andyone** [comment]
Hi! This image was created using **Svarog**, our internal tool. It's not open source, but you can download a pre-built version of it from [our applications repository](https://apps.kaos.st/svarog/).

**Comment by ccoVeille** [comment]
If you are looking for oprm source project

I would recommend using, one of these

https://github.com/charmbracelet/freeze

https://github.com/faressoft/terminalizer

**Comment by andyone** [comment]
> If you are looking for open source project, I would recommend using, one of these
> 
> https://github.com/charmbracelet/freeze
> 
> https://github.com/faressoft/terminalizer

None of them can provide the same features as `Svarog`. Terminalizer can't generate SVG images. SVG images generated by `freeze` are much bigger in size due to embedded font, have no support of internalised application (_for example, image from original question opened in browser with Russian as default language will show help content in Russian as it is displayed by the application on the system with_ `LANG=ru_RU.UTF-8`) and have no automatic theme switching based on browser mode (_try to open image with dark mode and without it_).

**Comment by ccoVeille** [comment]
Indeed, very interesting.

Any hope you open-source svarog?

**Comment by andyone** [comment]
I will think about it.
